language: minimal
services: docker

env:
  global:
    - CURL_VERSION='7.67.0'

matrix:
  include:
    - env: ARCH='amd64'   DOCKER_IMAGE='alpine'
    - env: ARCH='i386'    DOCKER_IMAGE='i386/alpine'
    - env: ARCH='aarch64' DOCKER_IMAGE='alpine'
      arch: arm64

script:
  - ./docker_build.sh "$DOCKER_IMAGE" "$ARCH" "$CURL_VERSION"

deploy:
  api_key:
    secure: $GITHUB_OAUTH
  file_glob: true
  file: curl*
  on:
    tags: true
  provider: releases
  skip_cleanup: true
